name: Dpay nginx hello Deployment

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: nginx-hello
  CONTAINER_NAME: nginx-hello

jobs:
  build-and-run:
    runs-on: self-hosted 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Stop & Remove Existing Container (if any)
        run: |
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true

      - name: Run Docker Container
        run: |
          docker run -d --name $CONTAINER_NAME -p 80:80 $IMAGE_NAME
